config/routes.rb
Rails.application.routes.draw do

  root 'friends#index'

  get '/friends' => 'friends#index'
  get '/friend/new' => 'friends#new'
  post '/friend/new' => 'friends#create'
  get '/friends/:id/show' => 'friends#show', as: 'show_friend'
  get '/friends/:id/edit' => 'friends#edit', as: 'edit_friend'
  put '/friends/:id/edit' => 'friends#update', as: 'update_friend'
  get '/friends/:id' => 'friends#destroy', as: 'delete_friend'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  validates :name, presence: true
  validates :riot_id, presence: true, uniqueness: true
  validates :discord, presence: true, uniqueness: true
  validates :facebook, presence: true, uniqueness: true
  validates :twitter, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    @friends = Friend.all
  end

  def new
  end

  def create
    @friend = Friend.new(friend_data)
    if @friend.save
      redirect_to friends_path
    else
      render :index
    end
  end

  def show
    @friend = Friend.find(params[:id])
  end

  def edit
    @friend = Friend.find(params[:id])
  end

  def update
    @friend = Friend.find(params[:id])
    if @friend.update(friend_data)
      redirect_to friends_path
    else
      render :edit
    end
  end

  def destroy
    @friend = Friend.find(params[:id])
    if @friend.destroy
      redirect_to friends_path
    else
      render :index
    end
  end

  private

  def friend_data
    params.require(:friend).permit(:name, :riot_id, :discord, :facebook, :twitter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/edit.html.erb
<div class="form-container">
  <%= form_with scope: :friend, method: :put, local: true do |f| %>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Name %></div>
      <th class="text-field"><%= f.text_field :name %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Riot_ID, 'Riot ID' %></div>
      <th class="text-field"><%= f.text_field :riot_id %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Discord %></div>
      <th class="text-field"><%= f.text_field :discord %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Facebook %></div>
      <th class="text-field"><%= f.text_field :facebook %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Twitter %></div>
      <th class="text-field"><%= f.text_field :twitter %></th>
    </div>
    <div class="form-buttons-container">
      <%= f.submit :"EDIT" %>
      <button type="button" class="form-button"><%= link_to "BACK", friends_path %></button>
    </div>
  <% end %>
</div>

app/views/friends/index.html.erb
<head>
  <title><%= @title %></title>
</head>

<div class="friends-table">
  <div class="label-bar">
    <div class="label">NAME</div>
    <div class="label">RIOT ID</div>
    <div class="label">DISCORD</div>
    <div class="label">FACEBOOK</div>
    <div class="label">TWITTER</div>
    <div class="action-buttons">
      <button type="button" class="add-friend-button">
      <%= link_to "+", friend_new_path, title: "Add New Friend" %>
      </button>
    </div>
  </div>
  <div class="data-container">
  <% @friends.each do |friend| %>
    <div class="data-row">
      <div class="data"><%= friend.name %></div>
      <div class="data"><%= friend.riot_id %></div>
      <div class="data"><%= friend.discord %></div>
      <div class="data"><%= friend.facebook %></div>
      <div class="data"><%= friend.twitter %></div>
      <div class="action-buttons">
        <div class="view-btn"><%= link_to "V", show_friend_path(friend.id), title: "Show" %></div>
        <div class="edit-btn"><%= link_to "E", edit_friend_path(friend.id), title: "Edit" %></div>
        <div class="delete-btn"><%= link_to "D", delete_friend_path(friend.id), title: "Delete", method: :delete %></div>      
      </div>
    </div>
  <% end %>
</div>

app/views/friends/new.html.erb
<div class="form-container">
  <%= form_with scope: :friend, local: true do |f| %>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Name %></div>
      <th class="text-field"><%= f.text_field :name %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Riot_ID, 'Riot ID' %></div>
      <th class="text-field"><%= f.text_field :riot_id %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Discord %></div>
      <th class="text-field"><%= f.text_field :discord %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Facebook %></div>
      <th class="text-field"><%= f.text_field :facebook %></th>
    </div>
    <div class="edit-label">
      <div class="form-label"><%= f.label :Twitter %></div>
      <th class="text-field"><%= f.text_field :twitter %></th>
    </div>
    <div class="form-buttons-container">
      <%= f.submit :"ADD" %>
      <button type="button" class="form-button"><%= link_to "BACK", friends_path %></button>
    </div>
  <% end %>
</div>

app/views/friends/show.html.erb
<div class="show-container">
  <div class="close-bar"><button type="button" class="close-show"><%= link_to "X", friends_path %></button></div>
  <div class="basic-info">
    <div class="name-id">
      <div class="name"><%= @friend.name %></div>
      <div class="id"><%= @friend.riot_id %></div>
    </div>
  </div>
  <div class="other-info">
    <div class="info">
      <div class="discord-logo"></div>
      <div class="show-data"><%= @friend.discord %></div>
    </div>
    <div class="info">
      <div class="facebook-logo"></div>
      <div class="show-data"><%= @friend.facebook %></div>
    </div>
    <div class="info">
      <div class="twitter-logo"></div>
      <div class="show-data"><%= @friend.twitter %></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pewpew Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>